name: deploy-blog

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3.4.1
        with: 
          node-version: ">=16.16.0"
      - run: npm install

      - name: build app
        run: npm run build

      - name: copy .output file with scp
        uses: appleboy/scp-action@v0.0.1
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASS }}
          port: 22
          source: ".output/"
          target: ${{ secrets.REMOTE_TARGET }}
          
        
      
